#!/usr/bin/env python

import sys
#import os
#import os.path
import argparse
#from subprocess import Popen, call, PIPE, STDOUT
#import matplotlib.pyplot as plt
#import numpy as np
#import srw
#import pyfits
#from ppgplot import *


class App(object):
    '''
    Main application object for the project
    '''
    def __init__(self, args):
        '''
        Constructor
        '''
        super(App, self).__init__()
        self.args = args

        self.run()

    def run(self):
        '''
        Main function
        '''
        print 'Hello world!'

if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser()

        args = parser.parse_args()
        app = App(args)
    except KeyboardInterrupt:
        print >> sys.stderr, "Interrupt caught, exiting..."
        sys.exit(0)
